version: '2'

services:

  # db:
  #  restart: always
  #  image: postgres:9.6
  #  ports:
  #     - '5432:5432'
   # volumes:
   #   - './pgdata:/var/lib/postgresql/data/'

  web: &django
    restart: always
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    env_file: '.env'
    environment:
      - DJANGO_SETTINGS_MODULE=api_dados_radares.settings
    volumes:
      - .:/code
    expose:
      - "8000"
    # ports:
    #   - '8000:8000'
    depends_on:
      - redis

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./conf/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

  dash:
    restart: always
    build: dash
    command: 'python app.py'
    ports:
      - '8050:8050'

  # celeryworker:
  #   <<: *django
  #   depends_on:
  #     - redis
  #   command: 'python -m celery -A api_dados_radares worker -l debug -Q default'

  # flower:
  #   <<: *django
  #   depends_on:
  #     - redis
  #   ports:
  #     - "5555:5555"
  #   command: 'python -m celery -A api_dados_radares flower'

  # celerybeat:
  #   <<: *django
  #   depends_on:
  #     - redis
  #   command: 'python -m celery -A api_dados_radares beat -l debug'
    
  redis:
    restart: always
    container_name: 'redis'
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - './redisdata:/data'