# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRadares',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('lote', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=40, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('sentido', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_equip', models.CharField(blank=True, max_length=30, null=True)),
                ('enquadrame', models.CharField(blank=True, max_length=20, null=True)),
                ('qtde_fxs_f', models.IntegerField(blank=True, null=True)),
                ('data_publi', models.CharField(blank=True, max_length=24, null=True)),
                ('velocidade', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude_l', models.CharField(blank=True, max_length=50, null=True)),
                ('ligado', models.IntegerField(blank=True, null=True)),
                ('data_desli', models.CharField(blank=True, max_length=24, null=True)),
                ('motivo_des', models.CharField(blank=True, max_length=254, null=True)),
                ('mi_style', models.CharField(blank=True, max_length=254, null=True)),
                ('mi_prinx', models.IntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('emme_gid', models.IntegerField(blank=True, null=True)),
                ('mdc_gid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_radares',
            },
        ),
    ]
